### ISSUE TITLE
Warn on unused parameter on exported functions

### ISSUE THREAD

**Issue by martinlindhe** [tsenart/deadcode#6]
The current snippet gives warning `warning: some is unused`.

```
package p

import "fmt"

func some(s string, n int) {
    fmt.Println(s)
    // n is unused
}
```

However, if the function is exported, then there is no warning.

No warning:

```
package p

import "fmt"

func Some(s string, n int) {
    fmt.Println(s)
    // n is unused
}
```

**Comment by dnephin** [comment]
I think this would be by design. An exported function could be used by anyone who includes the package as a library, so unused exported methods are expected.

**Comment by martinlindhe** [comment]
@dnephin that sounds very sensible for me too, I think we can close this one.
